version: 2.0

jobs:
  validate:
    docker:
      - image: ruby
    steps:
      - checkout
      - run: make check

  build:docker:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t resources .

workflows:
  version: 2
  build:
    jobs:
      - validate
      - build:docker:
          requires:
            - validate
